### ISSUE TITLE
Create seeder and migration script

### ISSUE THREAD

**Issue by Exegetech** [Robert-Ramirez/todo-list#2]
Create seeder and migration script in folder
‘scripts’

Migration script is for doing db migration,
Seeder script is for seeding database with fake stuffs. Use fakerjs to generate fake data. Generate 1000 fake tasks

**Comment by Robert-Ramirez** [comment]
I updated the migration script in REST-API/dev-data/data/import-dev-data.js

**Comment by Robert-Ramirez** [comment]
I update the seeder script with fake stuff. REST-API/dev-data/data/import-faker.js

**Comment by Exegetech** [comment]
Rename it to `scripts/seed.js` instead, and put in package json

`seed: node scripts/seed.js`

**Comment by Robert-Ramirez** [comment]
done
