### ISSUE TITLE
Create a User model and API

### ISSUE THREAD

**Issue by Exegetech** [Robert-Ramirez/todo-list#4]
Create a User model in the database. A user needs to have:
- email
- password
- role (can only be two, either Admin or regular user)

Then change the Task model such that a User can have many Tasks.

Then implement the API CRUD endpoint.
GET `/users`
GET `/users/:id`
POST `/users`
PATCH `/users/:id`
PUT `/users:id`
DELETE `/users:id`

Because a Task cannot be created without a User, then you need to change the Task API endpoint such that
GET `/users/:userId/tasks`
GET `/users/:userId/tasks/:taskId`
POST `/users/:userId/tasks`
PUT `/users/:userId/tasks/:taskId`
PATCH `/users/:userId/tasks/:taskId`
DELETE `/users/:userId/tasks/:taskId`

**Comment by Robert-Ramirez** [comment]
updated for the most part. Need to review to make sure everything is fine.

**Comment by Exegetech** [comment]
Allright let me know if you are done so I can review

**Comment by Robert-Ramirez** [comment]
you can review now. I added proper authorization of role types via a new controller.
